post_upgrade() {
  echo "Enable NVIDIA GRID: systemctl enable --now nvidia-vgpu{d,-mgr}"
  echo "If you run into trouble with CUDA or GRID not being available, run nvidia-modprobe first."
  echo "If you use GDM on Wayland, you might have to run systemctl enable --now nvidia-resume.service"
}
# For the latter nore, see also https://gitlab.gnome.org/GNOME/gdm/-/issues/784

post_install() {
  post_upgrade
}

post_remove() {
  systemctl disable --now nvidia-vgpud nvidia-vgpu-mgr
}
